### ISSUE TITLE
[v0.8] Update witness tx logic for new event structure

### ISSUE THREAD

**Issue by hrharder** [ParadigmFoundation/ParadigmCore#40]
The new event structure will report absolute balances, rather than a change in balance. This will require the following changes:

- Before:
   ```ts
   // illustrative snippet
   
   function applyWitnessEvent(state: State, tx: ParsedWitnessTx): void {
     switch (tx.type) {
       case ("add"): {
         state.posters[tx.address].balance += tx.amount;
       }
       case ("remove"): {
         state.posters[tx.address].balance -= tx.amount;
       }
     }
   }
   ```

- After:
   ```ts
   // illustrative snippet
   
   function applyWitnessEvent(state: State, tx: ParsedWitnessTx): void {
     state.posters[tx.address].balance = tx.amount;
   }
   ```

- Not shown are the changes necessary to the witness class, and the `deliverTx()` handler(s) themselves.

**Comment by Freydal** [comment]
@hrharder I tried to get you going with the following.  Feel free to reset and overwrite this commit if I'm totally off.   https://github.com/ParadigmFoundation/ParadigmCore/commit/bf154a84ab37ada0ff9c28370f00138cad1b69ba

**Comment by hrharder** [comment]
All is well! made a few minor adjustments (already discussed) but everything else seems to work.

Main branch for v0.8 now is `v0.8-finalize`

See pr [here](https://github.com/ParadigmFoundation/ParadigmCore/issues/52#issuecomment-462572205) for additional commits.
