### ISSUE TITLE
[v0.8] Update witness class to use new EventEmitter contract, and ABI's via NPM exports

### ISSUE THREAD

**Issue by hrharder** [ParadigmFoundation/ParadigmCore#52]
## Overview
The latest version of the `internal` contract system uses module exports for contract ABI's and event decoder functions.

We can now replace the long `node_modules/...` import for the Contract ABI's with importing the default export of the contract package.

## Action items
- [x] @Freydal update NPM contract system
- [x] use new export to get `EventEmitter.sol` ABI
- [x] create `EventEmitter` instance in Witness class (in correct location)

**Comment by hrharder** [comment]
No immediate rush on this! `0.8` won't be ready til the new API is ready anyway.

**Comment by Freydal** [comment]
These two commits provide this: https://github.com/ParadigmFoundation/ParadigmCore/commit/9bc63ee37ddaa611d823a72a4596859ee4136ef4 & https://github.com/ParadigmFoundation/ParadigmCore/commit/380546159bf05884ac045066647996793f995be5

**Comment by hrharder** [comment]
Excellent! And [this](https://github.com/ParadigmFoundation/ParadigmCore/commit/bf154a84ab37ada0ff9c28370f00138cad1b69ba) all looks good to me as well (just visually - without running linter or pulling the branch). 

Were you able to get balances to update correctly or have you not gotten there yet?

**Comment by Freydal** [comment]
I don't think I got a correct update to go through correctly.  I may have missed something simple.  Haven't started debugging it yet.

**Comment by hrharder** [comment]
[`cff8e2c`](https://github.com/ParadigmFoundation/ParadigmCore/commit/cff8e2c03d215e5439ab118ff7824dfc94ef3f0c) should address the issue with `witness` tx's failing in the mempool

**Comment by hrharder** [comment]
We will also need to modify the `state` data structure (re `state.lastEvent`) since there is no longer a need to track `add` and `remove` events separately. I'll go ahead and make that change today or in the AM.

**Comment by hrharder** [comment]
Addressed prev. comment here: [`862a6c9`](https://github.com/ParadigmFoundation/ParadigmCore/commit/862a6c91ce99fae6ea519339e1d9c31ca69de3f0?diff=unified)

**Comment by hrharder** [comment]
Thinking we can close this now - I've started to use a new branch (`v0.8-finalize`) since the `tags` name was no longer accurate.

Thanks Nick!
